### PR TITLE
Adding capability to parse XML to avro using SAX parsing

### PR DESCRIPTION
**Pull request by vaughansharman**
This pull request adds the ability to parse XML documents to avro using a SAX parser

We had a requirement to parse very large xml files to avro, unfortunately the existing implementation uses DOM parsing which loads the entire document into memory. Because the SAX parser streams over a document this change allow very large files to be read and written to avro.

Please keep in mind that because we are streaming over the document this style of parsing is only really suitable for reading list style XML documents. There is no advantage using SAX when the whole XML file is a single item

All previous functionality (including DOM parsing) is still there, this just gives users more options and capability

### CODE REVIEW

**Comment by vaughansharman** [comment]
Do you think you will have a chance to look at this? Just need to know whether I should look into publishing my fork to a nexus repo separately...

**Comment by vaughansharman** [comment]
@dmitrypekar & @joestein adding you in case you did not receive a notification previously...

**Comment by joestein** [comment]
@vaughansharman hey sorry just got to seeing this, we should be able to test it this week and publish it to maven next. We have a bunch of other updates that have been worked on around to integrate back into this too.

**Comment by vaughansharman** [comment]
no worries

**Comment by vaughansharman** [comment]
closing as it has been quite a while

**Pull request closed without merging**
